#spring.application.name

spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://localhost:3306/user_center
    username: root
    password: Zhangbin0327
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080